services:
  - type: web
    name: chirasha-art-gallery
    runtime: node
    plan: free
    buildCommand: npm install && npm run build --prefix client
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
